spring:
  application:
    name: karte-docs
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/karte_docs_db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: ${SERVER_PORT:8080}
  address: 0.0.0.0
  servlet:
    context-path: /api/v1

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}